### PR TITLE
Correct Redundancies in Loops

### PR DESCRIPTION
**Pull request by menoliu**
Will look for other instances of this issue. First commit has been tested and works as expected.

### CODE REVIEW

**Comment by menoliu** [comment]
@joaomcteixeira , I have refactored the loops that are redundant. Great suggestions, I've combed through all the `cli`s and have cleaned up what I can, let me know if you find anything else that I might've missed. Cheers!

**Review by joaomcteixeira — APPROVED** [review]
Great work! add to changelog and done :+1:

**Comment by menoliu** [comment]
Thanks for the reminder @joaomcteixeira

**Comment by joaomcteixeira** [comment]
Only the lint from #229 is present. merging.

**Pull request merged**
